#Goal: Test Application on  Multiple Version on Multiple OS
name: Matrix Strategy Demo
on: [push, pull_request]

#declaring strategy block

jobs:
  Multi-Tasking:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [18, 20, 22]

    steps:
      - name: checkout the repsitory code
        uses: actions/checkout@v4

      - name: Setup node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}


      - name: Install dependencies and run tests
        run: |
          npm ci
          npm test

